### ISSUE TITLE
Note ON with velocity 0 should be parsed as NoteOff

### ISSUE THREAD

**Issue by jmyhrman** [RustAudio/wmidi#5]
Calling wmidi::MidiMessage::try_from() on a raw Note ON message with velocity 0 currently returns a Note ON message.

According to the MIDI spec, a Note ON message with velocity 0 should be treated as a Note OFF message:
https://www.midi.org/forum/228-writing-midi-software-send-note-off

Do you consider this as a responsibility of the wmidi library, or a responsibility of the application?

I would suggest it is responsibility of the library, with two primary reasons:
 - NoteOn message with velocity 0 is not really a valid logical message from a high-level perspective.
 - Users who are unaware of this requirement may observe compatibility issues with MIDI hardware that only sends NoteOn with vel=0 instead of actual NoteOff message. Change in library would fix this everywhere.

Example sequence, expected result:
[144, 60, 127] => Ok(NoteOn(Ch1, C4(60), U7(127)))
[144, 60, 0] => Ok(NoteOff(Ch1, C4(60), U7(0)))

Example sequence, actual result:
[144, 60, 127] => Ok(NoteOn(Ch1, C4(60), U7(127)))
[144, 60, 0] => Ok(NoteOn(Ch1, C4(60), U7(0)))

**Comment by wmedrano** [comment]
If midi devices are indeed sending NoteOn(0) messages than it is worth interpretting as NoteOff at decode time. Working on a fix.

**Comment by wmedrano** [comment]
This is live in version 4.0.2.

**Comment by jmyhrman** [comment]
Excellent, thanks for the quick fix!
